name: 'nyc_taxi_pipeline'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi_pipeline:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: analytics
